import type { Tool } from '@prisma/client';

const now = new Date('2026-02-27T00:00:00.000Z');

function buildTool(tool: Omit<Tool, 'createdAt' | 'updatedAt'>): Tool {
  return { ...tool, createdAt: now, updatedAt: now };
}

export const popularToolsCatalog: Tool[] = [
  buildTool({
    id: 'catalog-chatgpt',
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'General-purpose AI assistant for writing, research, ideation, and production workflows.',
    category: 'writing',
    pricingType: 'freemium',
    pricingDetails: 'Free tier available with paid Plus/Pro tiers.',
    pros: ['Fast ideation', 'Strong multimodal workflow support'],
    cons: ['Output quality depends on prompt quality'],
    bestFor: 'Creators and operators building repeatable content systems',
    affiliateUrl: 'https://openai.com/chatgpt/',
    featured: true
  }),
  buildTool({
    id: 'catalog-claude',
    name: 'Claude',
    slug: 'claude',
    description: 'AI assistant commonly used for long-form writing, analysis, and structured drafting.',
    category: 'writing',
    pricingType: 'freemium',
    pricingDetails: 'Free tier and paid Pro plans available.',
    pros: ['Strong long-context drafting', 'Helpful for editing and reasoning'],
    cons: ['Quality varies by prompt structure'],
    bestFor: 'Writers and creators who need clean long-form outputs',
    affiliateUrl: 'https://www.anthropic.com/claude',
    featured: true
  }),
  buildTool({
    id: 'catalog-midjourney',
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'AI image generation platform for concept art, thumbnails, and visual ideation.',
    category: 'image',
    pricingType: 'paid',
    pricingDetails: 'Paid subscription plans.',
    pros: ['High quality stylized imagery', 'Strong creative control'],
    cons: ['Requires prompt iteration'],
    bestFor: 'Design-first creators and brand visual exploration',
    affiliateUrl: 'https://www.midjourney.com/',
    featured: true
  }),
  buildTool({
    id: 'catalog-canva-ai',
    name: 'Canva AI',
    slug: 'canva-ai',
    description: 'AI-assisted design suite for social graphics, slides, and content packaging.',
    category: 'image',
    pricingType: 'freemium',
    pricingDetails: 'Free plan with paid Pro upgrades.',
    pros: ['Fast design workflows', 'Template-driven consistency'],
    cons: ['Advanced customization can be limited'],
    bestFor: 'Creators shipping multi-platform visual content quickly',
    affiliateUrl: 'https://www.canva.com/magic-studio/',
    featured: true
  }),
  buildTool({
    id: 'catalog-descript',
    name: 'Descript',
    slug: 'descript',
    description: 'Text-based audio and video editor used for podcast and short-form clipping workflows.',
    category: 'video',
    pricingType: 'freemium',
    pricingDetails: 'Free tier with paid creator and business plans.',
    pros: ['Transcript-first editing', 'Great for repurposing'],
    cons: ['Advanced editing requires setup'],
    bestFor: 'Podcast and video teams creating clips at scale',
    affiliateUrl: 'https://www.descript.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-capcut-ai',
    name: 'CapCut AI',
    slug: 'capcut-ai',
    description: 'AI-assisted short-form video editor with captioning and mobile-friendly workflows.',
    category: 'video',
    pricingType: 'free',
    pricingDetails: 'Free tier with optional paid upgrades.',
    pros: ['Fast short-form edits', 'Strong subtitle workflow'],
    cons: ['Template-heavy outputs can feel repetitive'],
    bestFor: 'TikTok and Reels production teams',
    affiliateUrl: 'https://www.capcut.com/tools/video-editor',
    featured: false
  }),
  buildTool({
    id: 'catalog-zapier',
    name: 'Zapier',
    slug: 'zapier',
    description: 'No-code automation platform for connecting creator and marketing apps.',
    category: 'automation',
    pricingType: 'freemium',
    pricingDetails: 'Free and paid automation tiers.',
    pros: ['Large app ecosystem', 'Fast no-code automation setup'],
    cons: ['Complex automations can increase task usage costs'],
    bestFor: 'Automation between forms, CRMs, docs, and newsletters',
    affiliateUrl: 'https://zapier.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-make',
    name: 'Make',
    slug: 'make',
    description: 'Visual automation builder with branching logic and advanced scenario control.',
    category: 'automation',
    pricingType: 'freemium',
    pricingDetails: 'Free tier with paid operational scaling.',
    pros: ['Visual scenario design', 'Strong multi-step logic'],
    cons: ['Steeper learning curve than basic automation tools'],
    bestFor: 'Operators building complex no-code workflows',
    affiliateUrl: 'https://www.make.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-notion-ai',
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'Workspace AI assistant for planning, drafting, summarizing, and team documentation.',
    category: 'productivity',
    pricingType: 'freemium',
    pricingDetails: 'Workspace plans with optional AI add-on.',
    pros: ['Great for centralizing ops', 'Strong document workflows'],
    cons: ['Requires good workspace structure'],
    bestFor: 'Content ops and editorial planning systems',
    affiliateUrl: 'https://www.notion.com/product/ai',
    featured: false
  }),
  buildTool({
    id: 'catalog-beehiiv',
    name: 'Beehiiv',
    slug: 'beehiiv',
    description: 'Newsletter publishing platform focused on growth, segmentation, and monetization.',
    category: 'marketing',
    pricingType: 'freemium',
    pricingDetails: 'Free plan plus paid scale plans.',
    pros: ['Creator-focused newsletter stack', 'Built-in growth features'],
    cons: ['Advanced growth features require paid plans'],
    bestFor: 'Newsletter-first creator businesses',
    affiliateUrl: 'https://www.beehiiv.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-gemini',
    name: 'Google Gemini',
    slug: 'google-gemini',
    description: 'Google AI assistant used for research, drafting, and multimodal productivity tasks.',
    category: 'writing',
    pricingType: 'freemium',
    pricingDetails: 'Free access with advanced paid plans.',
    pros: ['Tight Google ecosystem integration', 'Useful for research and drafting'],
    cons: ['Best results need precise prompting'],
    bestFor: 'Creators and teams using Google Workspace',
    affiliateUrl: 'https://gemini.google.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-perplexity',
    name: 'Perplexity',
    slug: 'perplexity',
    description: 'AI answer engine with citations for fast research and source-backed briefs.',
    category: 'productivity',
    pricingType: 'freemium',
    pricingDetails: 'Free and Pro plans.',
    pros: ['Citation-first answers', 'Fast research workflow'],
    cons: ['Needs source validation for critical claims'],
    bestFor: 'Research sprints and fact-checked content prep',
    affiliateUrl: 'https://www.perplexity.ai/',
    featured: false
  }),
  buildTool({
    id: 'catalog-github-copilot',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI coding assistant for drafting code, tests, and implementation suggestions.',
    category: 'productivity',
    pricingType: 'freemium',
    pricingDetails: 'Free tier and paid plans available.',
    pros: ['Speeds up coding tasks', 'Integrated into common IDEs'],
    cons: ['Requires human code review and validation'],
    bestFor: 'Developers and technical creators shipping faster',
    affiliateUrl: 'https://github.com/features/copilot',
    featured: false
  }),
  buildTool({
    id: 'catalog-runway',
    name: 'Runway',
    slug: 'runway',
    description: 'AI video generation and editing platform for cinematic and marketing content.',
    category: 'video',
    pricingType: 'paid',
    pricingDetails: 'Paid plans with credits.',
    pros: ['Strong generative video features', 'Good creative experimentation'],
    cons: ['Output consistency requires iterative prompt tuning'],
    bestFor: 'Creative video teams and ad concept production',
    affiliateUrl: 'https://runwayml.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-elevenlabs',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice platform for narration, dubbing, and synthetic voice production.',
    category: 'customer_support',
    pricingType: 'freemium',
    pricingDetails: 'Free and paid tiers based on usage.',
    pros: ['High quality voice generation', 'Useful multilingual voice workflows'],
    cons: ['Voice quality depends on script and settings'],
    bestFor: 'Voiceover pipelines for podcasts and video',
    affiliateUrl: 'https://elevenlabs.io/',
    featured: false
  }),
  buildTool({
    id: 'catalog-synthesia',
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'AI avatar video platform for explainers, onboarding, and training content.',
    category: 'video',
    pricingType: 'paid',
    pricingDetails: 'Paid creator and business plans.',
    pros: ['Fast presenter-style video production', 'Scales training content'],
    cons: ['Avatar style may not fit every brand'],
    bestFor: 'Educational and product explainer video workflows',
    affiliateUrl: 'https://www.synthesia.io/',
    featured: false
  }),
  buildTool({
    id: 'catalog-heygen',
    name: 'HeyGen',
    slug: 'heygen',
    description: 'Avatar and synthetic presenter platform for tutorials, ads, and explainers.',
    category: 'video',
    pricingType: 'freemium',
    pricingDetails: 'Free trial and paid tiers.',
    pros: ['Quick avatar videos', 'Useful for localization workflows'],
    cons: ['Requires strong scripting for authenticity'],
    bestFor: 'Faceless tutorials and multi-language video output',
    affiliateUrl: 'https://www.heygen.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-jasper',
    name: 'Jasper',
    slug: 'jasper',
    description: 'AI marketing writing platform built for campaign and brand content teams.',
    category: 'marketing',
    pricingType: 'paid',
    pricingDetails: 'Paid plans for teams and campaigns.',
    pros: ['Marketing-focused templates', 'Brand voice controls'],
    cons: ['Best value for frequent campaign output'],
    bestFor: 'Campaign copy systems and brand content ops',
    affiliateUrl: 'https://www.jasper.ai/',
    featured: false
  }),
  buildTool({
    id: 'catalog-grammarly',
    name: 'Grammarly',
    slug: 'grammarly-ai',
    description: 'AI writing assistant for clarity, tone, grammar, and communication quality.',
    category: 'writing',
    pricingType: 'freemium',
    pricingDetails: 'Free and paid plans.',
    pros: ['Excellent editing layer', 'Consistent quality improvements'],
    cons: ['Needs human judgment for nuanced messaging'],
    bestFor: 'Final polish and tone consistency in creator writing',
    affiliateUrl: 'https://www.grammarly.com/',
    featured: false
  }),
  buildTool({
    id: 'catalog-fireflies',
    name: 'Fireflies AI',
    slug: 'fireflies-ai',
    description: 'Meeting intelligence tool for recording, transcription, and action extraction.',
    category: 'productivity',
    pricingType: 'freemium',
    pricingDetails: 'Free tier with paid upgrades.',
    pros: ['Meeting summaries and tasks', 'Easy team collaboration'],
    cons: ['Requires workflow discipline to act on insights'],
    bestFor: 'Turning calls into documented action plans',
    affiliateUrl: 'https://fireflies.ai/',
    featured: false
  })
];

export function getCatalogToolBySlug(slug: string): Tool | null {
  return popularToolsCatalog.find((tool) => tool.slug === slug) ?? null;
}
